insert into tests (language,block_name,description,follow_up_question) values ("eng","m2_focus_gaze","Does {{Lapse_eesnimi}} focus gaze on an object?","");
insert into tests (language,block_name,description,follow_up_question) values ("eng","m2_eyetrack_moving_object","Does {{Lapse_eesnimi}} follow movement with eye?","m3_turn_head_to_track_moving_object");
insert into tests (language,block_name,description,follow_up_question) values ("eng","m2_smile_while_talked_to","Does {{Lapse_eesnimi}} smile while talked to?","");
insert into tests (language,block_name,description,follow_up_question) values ("eng","m2_lift_head_when_on_tummy","Can {{Lapse_eesnimi}} lift the head up, when lying the tummy?","");
insert into tests (language,block_name,description,follow_up_question) values ("eng","m2_startle_when_hears_sound","Does {{Lapse_eesnimi}} listen up, when sounds heard?","");
insert into tests (language,block_name,description,follow_up_question) values ("eng","m2_cooing","Does {{Lapse_eesnimi}} coo (make vowel sounds like ah-ah or oh-oh)?","");
insert into tests (language,block_name,description,follow_up_question) values ("eng","m3_turn_head_to_track_moving_object","Does {{Lapse_eesnimi}} turn head to track moving object?","");
insert into tests (language,block_name,description,follow_up_question) values ("eng","m3_smile_in_resonse_to_talk","Does {{Lapse_eesnimi}} smile back in response to talk?","");
insert into tests (language,block_name,description,follow_up_question) values ("eng","m3_hold_head_up_if_pulled_to_sit","Does {{Lapse_eesnimi}} hold the head up when pulled to sitting position?","");
insert into tests (language,block_name,description,follow_up_question) values ("eng","m3_lift_head_shoulders_when_lying_on_arms","Does {{Lapse_eesnimi}} lift head and shoulders high while lying on tummy and using arms for support?","");
insert into tests (language,block_name,description,follow_up_question) values ("eng","m3_stretch_body_to_both_sides","Does {{Lapse_eesnimi}} stretch the body to both sides?","");
insert into tests (language,block_name,description,follow_up_question) values ("eng","m3_respond_making_sound","Does {{Lapse_eesnimi}} respond to talk with a sound?","");
insert into tests (language,block_name,description,follow_up_question) values ("eng","m5_grab_a_toy","Does {{Lapse_eesnimi}} grab a toy?","");
insert into tests (language,block_name,description,follow_up_question) values ("eng","m5_haaramisrefleksi_kadumine","tbd","");
insert into tests (language,block_name,description,follow_up_question) values ("eng","m5_imemisrefleksi_kadumine","tbd","");
insert into tests (language,block_name,description,follow_up_question) values ("eng","m5_flip_from_back_to_side","Does {{Lapse_eesnimi}} flip over from belly to side?","m6_rolling_over_back_to_front_to_back");
insert into tests (language,block_name,description,follow_up_question) values ("eng","m5_finding_sound_source","Does {{Lapse_eesnimi}} try to figure out, where a sound came from?","m6_turn_head_towards_sound");
insert into tests (language,block_name,description,follow_up_question) values ("eng","m6_rolling_over_back_to_front_to_back","Does {{Lapse_eesnimi}} roll over form belly to back or back to belly?","m8_getting_on_allfours");
insert into tests (language,block_name,description,follow_up_question) values ("eng","m6_transfer_toy_from_one_hand_to_other","Does {{Lapse_eesnimi}} transfer a toy from one hand to the other?","");
insert into tests (language,block_name,description,follow_up_question) values ("eng","m6_eat_spoonfed","Does {{Lapse_eesnimi}} eat when spoonfed?","");
insert into tests (language,block_name,description,follow_up_question) values ("eng","m6_babbling","Does {{Lapse_eesnimi}} babble (make sounds like bah-bah and nah-nah)?","");
insert into tests (language,block_name,description,follow_up_question) values ("eng","m6_turn_head_towards_sound","Does {{Lapse_eesnimi}} turn the head towards a noise source?","m8_turning_towards_pointed_direction");
insert into tests (language,block_name,description,follow_up_question) values ("eng","m7_drink_sips_from_cup","Does {{Lapse_eesnimi}} drink sips from cup when offered?","m12_drink_from_cup");
insert into tests (language,block_name,description,follow_up_question) values ("eng","m8_getting_on_allfours","Does {{Lapse_eesnimi}} get down on all fours?","m9_crawling");
insert into tests (language,block_name,description,follow_up_question) values ("eng","m8_grabbing_thing_with_both_hands","Does {{Lapse_eesnimi}} grab things with both hands?","");
insert into tests (language,block_name,description,follow_up_question) values ("eng","m8_saying_syllable_sequences","Does {{Lapse_eesnimi}} babble sequences of syllables (ma-ma-ma)?","m9_babble_4syllables");
insert into tests (language,block_name,description,follow_up_question) values ("eng","m8_combining_syllables","Does {{Lapse_eesnimi}} combine syllables and sounds (ma-da-ba)?","m9_babble_4syllables");
insert into tests (language,block_name,description,follow_up_question) values ("eng","m8_turning_towards_pointed_direction","Does {{Lapse_eesnimi}} turn towards pointed direction?","");
insert into tests (language,block_name,description,follow_up_question) values ("eng","m9_sit_unsupported","Does {{Lapse_eesnimi}} sit without support?","");
insert into tests (language,block_name,description,follow_up_question) values ("eng","m9_crawling","Does {{Lapse_eesnimi}} crawl?","");
insert into tests (language,block_name,description,follow_up_question) values ("eng","m9_stand_up_from_sitting_without_support","Does {{Lapse_eesnimi}} stand up from sitting with support?","m12_stand_unsupported");
insert into tests (language,block_name,description,follow_up_question) values ("eng","m9_fear_strangers","Does {{Lapse_eesnimi}} know difference between familiar and strage people?","");
insert into tests (language,block_name,description,follow_up_question) values ("eng","m9_point_and_demand_things","Does {{Lapse_eesnimi}} point to things the baby sees or wants and make demanding sounds?","");
insert into tests (language,block_name,description,follow_up_question) values ("eng","m9_demand_attention","Does {{Lapse_eesnimi}} try to get your attention and get what the baby wants?","");
insert into tests (language,block_name,description,follow_up_question) values ("eng","m9_babble_4syllables","Does {{Lapse_eesnimi}} babble 4 or more different syllables?","m18_say_4to6_words");
insert into tests (language,block_name,description,follow_up_question) values ("eng","m12_stand_unsupported","Does {{Lapse_eesnimi}} stand up without support?","");
insert into tests (language,block_name,description,follow_up_question) values ("eng","m12_walk unsupported","Does {{Lapse_eesnimi}} walk without support?","m24_jump_on_2_feet");
insert into tests (language,block_name,description,follow_up_question) values ("eng","m12_grab_small_things_with_fingers","Does {{Lapse_eesnimi}} grab little things with fingers?","");
insert into tests (language,block_name,description,follow_up_question) values ("eng","m12_eat_from_spoon","Does {{Lapse_eesnimi}} eat from spoon?","");
insert into tests (language,block_name,description,follow_up_question) values ("eng","m12_drink_from_cup","Does {{Lapse_eesnimi}} drink from cup?","");
insert into tests (language,block_name,description,follow_up_question) values ("eng","m18_walk_independently","Does {{Lapse_eesnimi}} walk unsupported and confidently?","");
insert into tests (language,block_name,description,follow_up_question) values ("eng","m18_stack_tower_items","Does {{Lapse_eesnimi}} place 2-3 toy blocks on top of each other or stack objects on top of one another?","");
insert into tests (language,block_name,description,follow_up_question) values ("eng","m18_eat_with_spoon_independently","Does {{Lapse_eesnimi}} eat from spoon independently?","m24_eat_independently");
insert into tests (language,block_name,description,follow_up_question) values ("eng","m18_signal_need_to_potty","Does {{Lapse_eesnimi}} let you know when needs to go to potty?","m24_go_to_toilet_independently");
insert into tests (language,block_name,description,follow_up_question) values ("eng","m18_diaper_dry_all_day","Does {{Lapse_eesnimi}} keep the diaper dry throughout the day?","");
insert into tests (language,block_name,description,follow_up_question) values ("eng","m18_say_4to6_words","Does {{Lapse_eesnimi}} say 4-6 words?","m24_combine_2_words_into_sentence");
insert into tests (language,block_name,description,follow_up_question) values ("eng","m18_repeat_heard_words","Does {{Lapse_eesnimi}} repeat words after you?","");
insert into tests (language,block_name,description,follow_up_question) values ("eng","m24_say_name","Does {{Lapse_eesnimi}} say his/her name?","");
insert into tests (language,block_name,description,follow_up_question) values ("eng","m24_jump_on_2_feet","Does {{Lapse_eesnimi}} jump up on 2 feet?","");
insert into tests (language,block_name,description,follow_up_question) values ("eng","m24_open_door","Can {{Lapse_eesnimi}} open doors?","");
insert into tests (language,block_name,description,follow_up_question) values ("eng","m24_undress_unassisted","Does {{Lapse_eesnimi}} remove clothing items independently?","");
insert into tests (language,block_name,description,follow_up_question) values ("eng","m24_eat_independently","Can {{Lapse_eesnimi}} eat independently?","");
insert into tests (language,block_name,description,follow_up_question) values ("eng","m24_go_to_toilet_independently","Can {{Lapse_eesnimi}} go to the toilet independently?","");
insert into tests (language,block_name,description,follow_up_question) values ("eng","m24_combine_2_words_into_sentence","Does {{Lapse_eesnimi}} combine 2 words into sentence?","m36_converse");
insert into tests (language,block_name,description,follow_up_question) values ("eng","m36_draw_circle","Can {{Lapse_eesnimi}} dray a circle?","");
insert into tests (language,block_name,description,follow_up_question) values ("eng","m36_name_colors","Can {{Lapse_eesnimi}} name colors?","");
insert into tests (language,block_name,description,follow_up_question) values ("eng","m36_answer_yes_no_questions","Can {{Lapse_eesnimi}} answer 'who?' 'or what?' questions?","");
insert into tests (language,block_name,description,follow_up_question) values ("eng","m36_converse","Does {{Lapse_eesnimi}} participate in a conversation?","");