insert into milestones (target_age,type,description) values (2,'NA','{{Lapse_eesnimi}} oskab fikseerida pilku esemele.');
insert into milestones (target_age,type,description) values (2,'NA','{{Lapse_eesnimi}} oskab jälgida pilguga liikuvat eset');
insert into milestones (target_age,type,description) values (2,'NA','{{Lapse_eesnimi}} oskab naeratada, kui teda kõnetatakse.');
insert into milestones (target_age,type,description) values (2,'NA','{{Lapse_eesnimi}} oskab tõsta kõhuliolekus pead.');
insert into milestones (target_age,type,description) values (2,'NA','{{Lapse_eesnimi}} oskab kuulatada, kui kostub heli.');
insert into milestones (target_age,type,description) values (2,'NA','{{Lapse_eesnimi}} oskab koogata (ühetooniliselt häälitseda).');
insert into milestones (target_age,type,description) values (3,'NA','{{Lapse_eesnimi}} oskab jälgida liikuvaid esemeid.');
insert into milestones (target_age,type,description) values (3,'NA','{{Lapse_eesnimi}} oskab naeratada kui keegi teda kõnetab.');
insert into milestones (target_age,type,description) values (3,'NA','{{Lapse_eesnimi}} oskab hoida pead kui ta kätest istukile tõmmata.');
insert into milestones (target_age,type,description) values (3,'NA','{{Lapse_eesnimi}} oskab kõhuliolekus tõsta pead ja õlavöödet, toetudes küünarvartele.');
insert into milestones (target_age,type,description) values (3,'NA','{{Lapse_eesnimi}} oskab painutada keha mõlemale küljele.');
insert into milestones (target_age,type,description) values (3,'NA','{{Lapse_eesnimi}} oskab vastata kõnele häälitsusega.');
insert into milestones (target_age,type,description) values (4.5,'NA','{{Lapse_eesnimi}} oskab haarata mänguasja.');
insert into milestones (target_age,type,description) values (4.5,'NA','{{Lapse_eesnimi}} oskab keerata seljalt küljele.');
insert into milestones (target_age,type,description) values (4.5,'NA','{{Lapse_eesnimi}} oskab proovida aru saada, kust tuleb heli.');
insert into milestones (target_age,type,description) values (6,'NA','{{Lapse_eesnimi}} oskab keerata seljalt kõhule ja tagasi.');
insert into milestones (target_age,type,description) values (6,'NA','{{Lapse_eesnimi}} oskab panna mänguasja ühest käest teise.');
insert into milestones (target_age,type,description) values (6,'NA','{{Lapse_eesnimi}} oskab süüa lusikast.');
insert into milestones (target_age,type,description) values (6,'NA','{{Lapse_eesnimi}} oskab laliseda.');
insert into milestones (target_age,type,description) values (6,'NA','{{Lapse_eesnimi}} oskab keerata pea sinna poole, kust tuleb heli.');
insert into milestones (target_age,type,description) values (7,'NA','{{Lapse_eesnimi}} oskab lonksu haaval tassist juua.');
insert into milestones (target_age,type,description) values (8,'NA','{{Lapse_eesnimi}} oskab võtta neljakäpukil asendi.');
insert into milestones (target_age,type,description) values (8,'NA','{{Lapse_eesnimi}} oskab võtta asju mõlema käega.');
insert into milestones (target_age,type,description) values (8,'NA','{{Lapse_eesnimi}} oskab ütelda silbirida.');
insert into milestones (target_age,type,description) values (8,'NA','{{Lapse_eesnimi}} oskab kombineerida silpe.');
insert into milestones (target_age,type,description) values (8,'NA','{{Lapse_eesnimi}} oskab vaadata osutatud suunas.');
insert into milestones (target_age,type,description) values (9,'NA','{{Lapse_eesnimi}} oskab tõusta ise istukile.');
insert into milestones (target_age,type,description) values (9,'NA','{{Lapse_eesnimi}} oskab roomata.');
insert into milestones (target_age,type,description) values (9,'NA','{{Lapse_eesnimi}} oskab toe najal püsti tõusta.');
insert into milestones (target_age,type,description) values (9,'NA','{{Lapse_eesnimi}} oskab eeristada omasid võõrastest.');
insert into milestones (target_age,type,description) values (9,'NA','{{Lapse_eesnimi}} oskab osutada asjadele, mida soovib ja teha nõudvaid häälitsusi.');
insert into milestones (target_age,type,description) values (9,'NA','{{Lapse_eesnimi}} oskab nõuda tähelepanu ja oma tahtmist.');
insert into milestones (target_age,type,description) values (9,'NA','{{Lapse_eesnimi}} oskab laliseda 4 või rohkem erinevat silpi.');
insert into milestones (target_age,type,description) values (12,'NA','{{Lapse_eesnimi}} oskab seista iseseisvalt püsti.');
insert into milestones (target_age,type,description) values (12,'NA','{{Lapse_eesnimi}} oskab iseseisvalt kõndida.');
insert into milestones (target_age,type,description) values (12,'NA','{{Lapse_eesnimi}} oskab haarata sõrmedega väikesi asju.');
insert into milestones (target_age,type,description) values (12,'NA','{{Lapse_eesnimi}} oskab süüa lusikast.');
insert into milestones (target_age,type,description) values (12,'NA','{{Lapse_eesnimi}} oskab juua tassist.');
insert into milestones (target_age,type,description) values (18,'NA','{{Lapse_eesnimi}} oskab vabalt ja kindlalt kõndida.');
insert into milestones (target_age,type,description) values (18,'NA','{{Lapse_eesnimi}} oskab laduda 2-3 klotsist torni või panna asju üksteise peale.');
insert into milestones (target_age,type,description) values (18,'NA','{{Lapse_eesnimi}} oskab süüa ise lusikast.');
insert into milestones (target_age,type,description) values (18,'NA','{{Lapse_eesnimi}} oskab anda märku kui on vaja potile minna.');
insert into milestones (target_age,type,description) values (18,'NA','{{Lapse_eesnimi}} oskab päeval mähkme kuiva hoida');
insert into milestones (target_age,type,description) values (18,'NA','{{Lapse_eesnimi}} oskab ütelda 4-6 sõna.');
insert into milestones (target_age,type,description) values (18,'NA','{{Lapse_eesnimi}} oskab korrata etteöeldud sõnu.');
insert into milestones (target_age,type,description) values (24,'NA','{{Lapse_eesnimi}} oskab ütelda oma nime.');
insert into milestones (target_age,type,description) values (24,'NA','{{Lapse_eesnimi}} oskab kahel jalal hüpata.');
insert into milestones (target_age,type,description) values (24,'NA','{{Lapse_eesnimi}} oskab ise ust avada.');
insert into milestones (target_age,type,description) values (24,'NA','{{Lapse_eesnimi}} oskab ise lahti riietuda.');
insert into milestones (target_age,type,description) values (24,'NA','{{Lapse_eesnimi}} oskab iseseisvalt süüa.');
insert into milestones (target_age,type,description) values (24,'NA','{{Lapse_eesnimi}} oskab ise potil käia.');
insert into milestones (target_age,type,description) values (24,'NA','{{Lapse_eesnimi}} oskab ütelda kahesõnalisi lauseid.');
insert into milestones (target_age,type,description) values (36,'NA','{{Lapse_eesnimi}} oskab joonistada ringi.');
insert into milestones (target_age,type,description) values (36,'NA','{{Lapse_eesnimi}} oskab nimetada värve.');
insert into milestones (target_age,type,description) values (36,'NA','{{Lapse_eesnimi}} oskab vastata kes? mis? küsimustele.');
insert into milestones (target_age,type,description) values (36,'NA','{{Lapse_eesnimi}} oskab vestluses osaleda.');