insert into tests (channel,block_name,description,follow_up_question) values ("chatbot","m5_asja_haaramine","Kas {{Lapse_eesnimi}} haarab mänguasja?","tbd");
insert into tests (channel,block_name,description,follow_up_question) values ("tbd","m5_haaramisrefleksi_kadumine","Kui puudutada lapse peopesa, kas ta surub käe kokku (haaramisrefleks)?","tbd");
insert into tests (channel,block_name,description,follow_up_question) values ("tbd","m5_imemisrefleksi_kadumine","Kui puudutada lapse põske, kas ta püüab suuga haarata (imemisrefleks)?","tbd");
insert into tests (channel,block_name,description,follow_up_question) values ("chatbot","m5_seljalt_kyljele_keeramine","Kas {{Lapse_eesnimi}} keerab seljalt küljele?","m6_seljalt_kohule_ja_tagasi_pooramine");
insert into tests (channel,block_name,description,follow_up_question) values ("chatbot","m5_heli_allika_leidmise_proovimine","Kas {{Lapse_eesnimi}} proovib aru saada, kust heli tuleb?","m6_pea_heli_poole_keeramine");
insert into tests (channel,block_name,description,follow_up_question) values ("chatbot","m6_seljalt_kohule_ja_tagasi_pooramine","Kas {{Lapse_eesnimi}} pöörab seljalt kõhule ja tagasi?","m8_neljakapukil_asendi_votmine");
insert into tests (channel,block_name,description,follow_up_question) values ("chatbot","m6_asja_yhest_kaest_teise_panemine","Kas {{Lapse_eesnimi}} paneb mänguasju ühest käest teise?","tbd");
insert into tests (channel,block_name,description,follow_up_question) values ("chatbot","m6_lusikast_soomine","Kas {{Lapse_eesnimi}} sööb lusikast?","tbd");
insert into tests (channel,block_name,description,follow_up_question) values ("chatbot","m6_lalisemine","Kas {{Lapse_eesnimi}} oskab laliseda?","tbd");
insert into tests (channel,block_name,description,follow_up_question) values ("chatbot","m6_pea_heli_poole_keeramine","Kas {{Lapse_eesnimi}} keerab pea sinna poole kus heli tuleb?","m8_osutatud_suunas_vaatamine");
insert into tests (channel,block_name,description,follow_up_question) values ("chatbot","m7_tassist_lonksuga_joomine","Kas {{Lapse_eesnimi}} oskab lonksu haaval tassist juua?","m12_tassist_joomine");
insert into tests (channel,block_name,description,follow_up_question) values ("chatbot","m8_neljakapukil_asendi_votmine","Kas {{Lapse_eesnimi}} oskab võtta neljakäpukil asendi?","m9_roomamine");
insert into tests (channel,block_name,description,follow_up_question) values ("chatbot","m8_asja_molema_kaega_votmine","Kas {{Lapse_eesnimi}} võtab asju mõlema käega?","tbd");
insert into tests (channel,block_name,description,follow_up_question) values ("chatbot","m8_silbirea_ytlemine","Kas {{Lapse_eesnimi}} ütleb silbirida (nt ba-ba või ga-ga)?","m9_lalisemine_4silpi");
insert into tests (channel,block_name,description,follow_up_question) values ("chatbot","m8_silpide_kombineerimine","Kas {{Lapse_eesnimi}} kombineerib silpe (nt ba-ma vi ba-ga)","m9_lalisemine_4silpi");
insert into tests (channel,block_name,description,follow_up_question) values ("chatbot","m8_osutatud_suunas_vaatamine","Kas {{Lapse_eesnimi}} oskab vaadata näidatud suunas?","tbd");
insert into tests (channel,block_name,description,follow_up_question) values ("chatbot","m9_istukile_tousmine","Kas {{Lapse_eesnimi}} tõuseb ise istuma?","tbd");
insert into tests (channel,block_name,description,follow_up_question) values ("chatbot","m9_roomamine","Kas {{Lapse_eesnimi}} roomab?","tbd");
insert into tests (channel,block_name,description,follow_up_question) values ("chatbot","m9_pusti_tousmine","Kas {{Lapse_eesnimi}} tuleb toe najal püsti?","tbd");
insert into tests (channel,block_name,description,follow_up_question) values ("chatbot","m9_vooristamine","Kas {{Lapse_eesnimi}} võõristab/eristab omasid võõrastest?","tbd");
insert into tests (channel,block_name,description,follow_up_question) values ("chatbot","m9_asjade_soovimine","Kas {{Lapse_eesnimi}} osutab asjadele, mida soovib ja teeb nõudvaid häälitsusi?","tbd");
insert into tests (channel,block_name,description,follow_up_question) values ("chatbot","m9_tahelepanu_soov_noudmine","Kas {{Lapse_eesnimi}} nõuab tähelepanu, proovib saada oma tahtmist?","tbd");
insert into tests (channel,block_name,description,follow_up_question) values ("chatbot","m9_lalisemine_4silpi","Kas {{Lapse_eesnimi}} laliseb 4 või rohkem erinevat silpi (nt la-ba-ga-da)?","tbd");
insert into tests (channel,block_name,description,follow_up_question) values ("chatbot","m12_pusti_seismine","Kas {{Lapse_eesnimi}} seisab iseseisvalt püsti?","tbd");
insert into tests (channel,block_name,description,follow_up_question) values ("chatbot","m12_ise_kondimine","Kas {{Lapse_eesnimi}} oskab juba iseseisvalt kõndida?","tbd");
insert into tests (channel,block_name,description,follow_up_question) values ("chatbot","m12_sormedega_vaikeste_asjade_haaramine","Kas {{Lapse_eesnimi}} oskab sõrmedega väikesi asju haarata?","tbd");
insert into tests (channel,block_name,description,follow_up_question) values ("chatbot","m12_lusikast_soomine","Kas {{Lapse_eesnimi}} oskab lusikast süüa?","m18_ise_lusikast_soomine");
insert into tests (channel,block_name,description,follow_up_question) values ("chatbot","m12_tassist_joomine","Kas {{Lapse_eesnimi}} oskab tassist juua?","tbd");
insert into tests (channel,block_name,description,follow_up_question) values ("chatbot","m18_ise_vabalt_kindlalt_kondimine","Kas {{Lapse_eesnimi}} kõnnib vabalt ja kindlalt?","tbd");
insert into tests (channel,block_name,description,follow_up_question) values ("chatbot","m18_torni_asjade_otsa_ladumine","Kas {{Lapse_eesnimi}} oskab laduda 2-3 klotsist torni või panna asju üksteise peale?","tbd");
insert into tests (channel,block_name,description,follow_up_question) values ("chatbot","m18_ise_lusikast_soomine","Kas {{Lapse_eesnimi}} sööb ise lusikast?","m24_ise_soomine");
insert into tests (channel,block_name,description,follow_up_question) values ("chatbot","m18_potile_minekust_marku_andmine","Kas {{Lapse_eesnimi}} annab märku kui on vaja potile minna?","tbd");
insert into tests (channel,block_name,description,follow_up_question) values ("chatbot","m18_mahe_kuiv_paeval","Kas {{Lapse_eesnimi}} (mähe) on päeval kuiv?","tbd");
insert into tests (channel,block_name,description,follow_up_question) values ("chatbot","m18_ytleb_4_10_sona","Kas {{Lapse_eesnimi}} oskab ütelda 4-10 sõna?","tbd");
insert into tests (channel,block_name,description,follow_up_question) values ("chatbot","m18_kordab_etteoeldud_sonu","Kas {{Lapse_eesnimi}} hakkab kordama etteöeldud sõnu?","tbd");
insert into tests (channel,block_name,description,follow_up_question) values ("chatbot","m24_eesnime_ytlemine","Kas {{Lapse_eesnimi}} oskab ütelda oma eesnime?","tbd");
insert into tests (channel,block_name,description,follow_up_question) values ("chatbot","m24_kahel_jalal_hyppamine","Kas {{Lapse_eesnimi}} oskab kahel jalal hüpata?","tbd");
insert into tests (channel,block_name,description,follow_up_question) values ("chatbot","m24_uste_avamine","Kas {{Lapse_eesnimi}} oskab ise ust avada?","tbd");
insert into tests (channel,block_name,description,follow_up_question) values ("chatbot","m24_lahti_riietumine_ise","Kas {{Lapse_eesnimi}} oskab ise lahti riietuda?","tbd");
insert into tests (channel,block_name,description,follow_up_question) values ("chatbot","m24_ise_soomine","Kas {{Lapse_eesnimi}} oskab iseseisvalt süüa?","tbd");
insert into tests (channel,block_name,description,follow_up_question) values ("chatbot","m24_ise_potil_kaimine","Kas {{Lapse_eesnimi}} käib ise potil?","tbd");
insert into tests (channel,block_name,description,follow_up_question) values ("chatbot","m24_kahesonaliste_lausete_ytlemine","Kas {{Lapse_eesnimi}} oskab ütelda kahesõnalisi lauseid (nt kass tuleb)","tbd");
insert into tests (channel,block_name,description,follow_up_question) values ("chatbot","m36_ringi_joonistamine","Kas {{Lapse_eesnimi}} oskab joonistada ringi?","tbd");
insert into tests (channel,block_name,description,follow_up_question) values ("chatbot","m36_varvide_nimetuste_tundmine","Kas {{Lapse_eesnimi}} tunneb värve (nimetusi)?","tbd");
insert into tests (channel,block_name,description,follow_up_question) values ("chatbot","m36_kes_mis_kysimustele_vastamine","Kas {{Lapse_eesnimi}} vastab kes? mis? küsimustele?","tbd");
insert into tests (channel,block_name,description,follow_up_question) values ("chatbot","m36_vestluses_osalemine","Kas {{Lapse_eesnimi}} oskab vestluses osaleda?","tbd");