insert into milestones (target_age,type,description) values (2,"NA","fikseerida pilku esemele");
insert into milestones (target_age,type,description) values (2,"NA","jälgida pilguga liikuvat eset");
insert into milestones (target_age,type,description) values (2,"NA","naeratada, kui teda kõnetatakse");
insert into milestones (target_age,type,description) values (2,"NA","tõsta kõhuliolekus pead");
insert into milestones (target_age,type,description) values (2,"NA","kuulatada, kui kostub heli");
insert into milestones (target_age,type,description) values (2,"NA","koogata (ühetooniliselt häälitseda)");
insert into milestones (target_age,type,description) values (3,"NA","jälgida liikuvaid esemeid");
insert into milestones (target_age,type,description) values (3,"NA","naeratada kui keegi teda kõnetab");
insert into milestones (target_age,type,description) values (3,"NA","hoida pead kui ta kätest istukile tõmmata");
insert into milestones (target_age,type,description) values (3,"NA","kõhuliolekus tõsta pead ja õlavöödet, toetudes küünarvartele");
insert into milestones (target_age,type,description) values (3,"NA","painutada keha mõlemale küljele");
insert into milestones (target_age,type,description) values (3,"NA","vastata kõnele häälitsusega");
insert into milestones (target_age,type,description) values (5,"NA","haarata mänguasja");
insert into milestones (target_age,type,description) values (500,"NA","tbd");
insert into milestones (target_age,type,description) values (500,"NA","tbd");
insert into milestones (target_age,type,description) values (5,"NA","keerata seljalt küljele");
insert into milestones (target_age,type,description) values (5,"NA","proovida aru saada, kust tuleb heli");
insert into milestones (target_age,type,description) values (6,"NA","keerata seljalt kõhule ja tagasi");
insert into milestones (target_age,type,description) values (6,"NA","panna mänguasja ühest käest teise");
insert into milestones (target_age,type,description) values (6,"NA","süüa lusikast");
insert into milestones (target_age,type,description) values (6,"NA","laliseda");
insert into milestones (target_age,type,description) values (6,"NA","keerata pea sinna poole, kust tuleb heli");
insert into milestones (target_age,type,description) values (7,"NA","lonksu haaval tassist juua");
insert into milestones (target_age,type,description) values (8,"NA","võtta neljakäpukil asendi");
insert into milestones (target_age,type,description) values (8,"NA","võtta asju mõlema käega");
insert into milestones (target_age,type,description) values (8,"NA","ütelda silbirida");
insert into milestones (target_age,type,description) values (8,"NA","kombineerida silpe");
insert into milestones (target_age,type,description) values (8,"NA","vaadata osutatud suunas");
insert into milestones (target_age,type,description) values (9,"NA","tõusta ise istukile");
insert into milestones (target_age,type,description) values (9,"NA","roomata");
insert into milestones (target_age,type,description) values (9,"NA","toe najal püsti tõusta");
insert into milestones (target_age,type,description) values (9,"NA","eeristada omasid võõrastest");
insert into milestones (target_age,type,description) values (9,"NA","osutada asjadele, mida soovib ja teha nõudvaid häälitsusi");
insert into milestones (target_age,type,description) values (9,"NA","nõuda tähelepanu ja oma tahtmist");
insert into milestones (target_age,type,description) values (9,"NA","laliseda 4 või rohkem erinevat silpi");
insert into milestones (target_age,type,description) values (12,"NA","seista iseseisvalt püsti");
insert into milestones (target_age,type,description) values (12,"NA","iseseisvalt kõndida");
insert into milestones (target_age,type,description) values (12,"NA","haarata sõrmedega väikesi asju");
insert into milestones (target_age,type,description) values (12,"NA","süüa lusikast");
insert into milestones (target_age,type,description) values (12,"NA","juua tassist");
insert into milestones (target_age,type,description) values (18,"NA","vabalt ja kindlalt kõndida");
insert into milestones (target_age,type,description) values (18,"NA","laduda 2-3 klotsist torni või panna asju üksteise peale");
insert into milestones (target_age,type,description) values (18,"NA","süüa ise lusikast");
insert into milestones (target_age,type,description) values (18,"NA","anda märku kui on vaja potile minna");
insert into milestones (target_age,type,description) values (18,"NA","päeval mähkme kuiva hoida");
insert into milestones (target_age,type,description) values (18,"NA","ütelda 4-6 sõna");
insert into milestones (target_age,type,description) values (18,"NA","korrata etteöeldud sõnu");
insert into milestones (target_age,type,description) values (24,"NA","ütelda oma nime");
insert into milestones (target_age,type,description) values (24,"NA","kahel jalal hüpata");
insert into milestones (target_age,type,description) values (24,"NA","ise ust avada");
insert into milestones (target_age,type,description) values (24,"NA","ise lahti riietuda");
insert into milestones (target_age,type,description) values (24,"NA","iseseisvalt süüa");
insert into milestones (target_age,type,description) values (24,"NA","ise potil käia");
insert into milestones (target_age,type,description) values (24,"NA","ütelda kahesõnalisi lauseid");
insert into milestones (target_age,type,description) values (36,"NA","joonistada ringi");
insert into milestones (target_age,type,description) values (36,"NA","nimetada värve");
insert into milestones (target_age,type,description) values (36,"NA","vastata kes? mis? küsimustele");
insert into milestones (target_age,type,description) values (36,"NA","vestluses osaleda");