insert into milestones (target_age,language,description) values (2,"est","fikseerida pilku esemele");
insert into milestones (target_age,language,description) values (2,"est","jälgida pilguga liikuvat eset");
insert into milestones (target_age,language,description) values (2,"est","naeratada, kui temaga kõneldakse");
insert into milestones (target_age,language,description) values (2,"est","tõsta kõhuliolekus pead");
insert into milestones (target_age,language,description) values (2,"est","kuulatada, kui kostub heli");
insert into milestones (target_age,language,description) values (2,"est","koogata (ühetooniliselt häälitseda)");
insert into milestones (target_age,language,description) values (3,"est","jälgida liikuvaid esemeid");
insert into milestones (target_age,language,description) values (3,"est","naeratada vastuseks, kui teda kõnetada");
insert into milestones (target_age,language,description) values (3,"est","hoida pead kui ta kätest istukile tõmmata");
insert into milestones (target_age,language,description) values (3,"est","kõhuliolekus tõsta pead ja õlavöödet, toetudes küünarvartele");
insert into milestones (target_age,language,description) values (3,"est","painutada keha mõlemale küljele");
insert into milestones (target_age,language,description) values (3,"est","vastata kõnele häälitsusega");
insert into milestones (target_age,language,description) values (5,"est","haarata mänguasja");
insert into milestones (target_age,language,description) values (500,"est","tbd");
insert into milestones (target_age,language,description) values (500,"est","tbd");
insert into milestones (target_age,language,description) values (5,"est","keerata seljalt küljele");
insert into milestones (target_age,language,description) values (5,"est","proovida aru saada, kust tuleb heli");
insert into milestones (target_age,language,description) values (6,"est","keerata seljalt kõhule ja tagasi");
insert into milestones (target_age,language,description) values (6,"est","panna mänguasja ühest käest teise");
insert into milestones (target_age,language,description) values (6,"est","süüa lusikast");
insert into milestones (target_age,language,description) values (6,"est","laliseda");
insert into milestones (target_age,language,description) values (6,"est","keerata pea sinna poole, kust tuleb heli");
insert into milestones (target_age,language,description) values (7,"est","lonksu haaval tassist juua");
insert into milestones (target_age,language,description) values (8,"est","võtta neljakäpukil asendit");
insert into milestones (target_age,language,description) values (8,"est","võtta asju mõlema käega");
insert into milestones (target_age,language,description) values (8,"est","ütelda silbirida");
insert into milestones (target_age,language,description) values (8,"est","kombineerida silpe");
insert into milestones (target_age,language,description) values (8,"est","vaadata osutatud suunas");
insert into milestones (target_age,language,description) values (9,"est","tõusta ise istukile");
insert into milestones (target_age,language,description) values (9,"est","roomata");
insert into milestones (target_age,language,description) values (9,"est","toe najal püsti tõusta");
insert into milestones (target_age,language,description) values (9,"est","eeristada omasid võõrastest");
insert into milestones (target_age,language,description) values (9,"est","osutada asjadele, mida soovib ja teha nõudvaid häälitsusi");
insert into milestones (target_age,language,description) values (9,"est","nõuda tähelepanu ja oma tahtmist");
insert into milestones (target_age,language,description) values (9,"est","laliseda 4 või rohkem erinevat silpi");
insert into milestones (target_age,language,description) values (12,"est","seista iseseisvalt püsti");
insert into milestones (target_age,language,description) values (12,"est","iseseisvalt kõndida");
insert into milestones (target_age,language,description) values (12,"est","haarata sõrmedega väikesi asju");
insert into milestones (target_age,language,description) values (12,"est","süüa lusikast");
insert into milestones (target_age,language,description) values (12,"est","juua tassist");
insert into milestones (target_age,language,description) values (18,"est","vabalt ja kindlalt kõndida");
insert into milestones (target_age,language,description) values (18,"est","laduda 2-3 klotsist torni või panna asju üksteise peale");
insert into milestones (target_age,language,description) values (18,"est","süüa ise lusikast");
insert into milestones (target_age,language,description) values (18,"est","anda märku kui on vaja potile minna");
insert into milestones (target_age,language,description) values (18,"est","päeval mähkme kuiva hoida");
insert into milestones (target_age,language,description) values (18,"est","ütelda 4-6 sõna");
insert into milestones (target_age,language,description) values (18,"est","korrata etteöeldud sõnu");
insert into milestones (target_age,language,description) values (24,"est","ütelda oma nime");
insert into milestones (target_age,language,description) values (24,"est","kahel jalal hüpata");
insert into milestones (target_age,language,description) values (24,"est","ise ust avada");
insert into milestones (target_age,language,description) values (24,"est","ise lahti riietuda");
insert into milestones (target_age,language,description) values (24,"est","iseseisvalt süüa");
insert into milestones (target_age,language,description) values (24,"est","ise potil käia");
insert into milestones (target_age,language,description) values (24,"est","ütelda kahesõnalisi lauseid");
insert into milestones (target_age,language,description) values (36,"est","joonistada ringi");
insert into milestones (target_age,language,description) values (36,"est","nimetada värve");
insert into milestones (target_age,language,description) values (36,"est","vastata kes? mis? küsimustele");
insert into milestones (target_age,language,description) values (36,"est","vestluses osaleda");
insert into milestones (target_age,language,description) values (2,"eng","focus gaze on an object");
insert into milestones (target_age,language,description) values (2,"eng","follow movement with eye");
insert into milestones (target_age,language,description) values (2,"eng","smile back, when talked to");
insert into milestones (target_age,language,description) values (2,"eng","lift head up, when lying on stomach");
insert into milestones (target_age,language,description) values (2,"eng","listen up, when sounds heard");
insert into milestones (target_age,language,description) values (2,"eng","coo (make vowel sounds like ah-ah or oh-oh)");
insert into milestones (target_age,language,description) values (3,"eng","turn head to track moving object");
insert into milestones (target_age,language,description) values (3,"eng","smile back in response to talk");
insert into milestones (target_age,language,description) values (3,"eng","hold the head up when pulled to sitting position");
insert into milestones (target_age,language,description) values (3,"eng","lift head and shoulders high while using arms for support");
insert into milestones (target_age,language,description) values (3,"eng","stretch the body to either side");
insert into milestones (target_age,language,description) values (3,"eng","respond to talk with a sound");
insert into milestones (target_age,language,description) values (5,"eng","grab a toy");
insert into milestones (target_age,language,description) values (500,"eng","tbd");
insert into milestones (target_age,language,description) values (500,"eng","tbd");
insert into milestones (target_age,language,description) values (5,"eng","flip over from belly to side");
insert into milestones (target_age,language,description) values (5,"eng","try to figure out, where a sound came from");
insert into milestones (target_age,language,description) values (6,"eng","roll over form belly to back or back to belly");
insert into milestones (target_age,language,description) values (6,"eng","transfer a toy from one hand to the other");
insert into milestones (target_age,language,description) values (6,"eng","eat when spoonfed");
insert into milestones (target_age,language,description) values (6,"eng","babble (make sounds like bah-bah and nah-nah)");
insert into milestones (target_age,language,description) values (6,"eng","turn head towards a noise source");
insert into milestones (target_age,language,description) values (7,"eng","drink sips from cup when offered");
insert into milestones (target_age,language,description) values (8,"eng","get down on all fours");
insert into milestones (target_age,language,description) values (8,"eng","grab things with either hand");
insert into milestones (target_age,language,description) values (8,"eng","babble sequences of syllables (ma-ma-ma)");
insert into milestones (target_age,language,description) values (8,"eng","combine syllables and sounds (ma-da-ba)");
insert into milestones (target_age,language,description) values (8,"eng","turn towards pointed direction");
insert into milestones (target_age,language,description) values (9,"eng","sit up without support");
insert into milestones (target_age,language,description) values (9,"eng","crawl");
insert into milestones (target_age,language,description) values (9,"eng","stand up from sitting with support");
insert into milestones (target_age,language,description) values (9,"eng","know difference between familiar and strage people");
insert into milestones (target_age,language,description) values (9,"eng","point to things the baby sees or wants and make demanding sounds");
insert into milestones (target_age,language,description) values (9,"eng","try to get your attention and get what the baby wants");
insert into milestones (target_age,language,description) values (9,"eng","babble 4 or more different syllables");
insert into milestones (target_age,language,description) values (12,"eng","stand up without support");
insert into milestones (target_age,language,description) values (12,"eng","walk without support");
insert into milestones (target_age,language,description) values (12,"eng","grab little things with fingers");
insert into milestones (target_age,language,description) values (12,"eng","eat from spoon");
insert into milestones (target_age,language,description) values (12,"eng","drink from cup");
insert into milestones (target_age,language,description) values (18,"eng","walk unsupported and confidently");
insert into milestones (target_age,language,description) values (18,"eng","place 2-3 toy blocks on top of each other or stack objects on top of one another");
insert into milestones (target_age,language,description) values (18,"eng","eat from spoon independently");
insert into milestones (target_age,language,description) values (18,"eng","let you know when needs to go to potty");
insert into milestones (target_age,language,description) values (18,"eng","keep the diaper dry throughout the day");
insert into milestones (target_age,language,description) values (18,"eng","say 4-6 words");
insert into milestones (target_age,language,description) values (18,"eng","repeat words");
insert into milestones (target_age,language,description) values (24,"eng","say his/her name");
insert into milestones (target_age,language,description) values (24,"eng","jump up on 2 feet");
insert into milestones (target_age,language,description) values (24,"eng","open doors");
insert into milestones (target_age,language,description) values (24,"eng","remove clothing items independently");
insert into milestones (target_age,language,description) values (24,"eng","eat independently");
insert into milestones (target_age,language,description) values (24,"eng","go to the toilet independently");
insert into milestones (target_age,language,description) values (24,"eng","combine 2 words into sentence");
insert into milestones (target_age,language,description) values (36,"eng","dray a circle");
insert into milestones (target_age,language,description) values (36,"eng","name colors");
insert into milestones (target_age,language,description) values (36,"eng","answer who? what? questions");
insert into milestones (target_age,language,description) values (36,"eng","participate in a conversation");